import { NextRequest, NextResponse } from "next/server";
import { promises as fs, existsSync } from "fs";
import path from "path";

// POST /api/storage/accept
// Receives a file forwarded from the Vercel deployment and saves it to
// private local storage (storage/uploads/).
// Protected by a shared secret (X-Storage-Secret header).
// This route only does useful work when running on the college server.
export async function POST(request: NextRequest) {
  // ── Auth: verify the shared secret ──
  const expectedSecret = process.env.STORAGE_SECRET;
  const incomingSecret = request.headers.get("X-Storage-Secret");

  if (!expectedSecret || incomingSecret !== expectedSecret) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  try {
    const formData = await request.formData();
    const file = formData.get("file") as File | null;
    const suggestedFilename = formData.get("filename") as string | null;

    if (!file) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    // Use the filename pre-generated by the Vercel upload route (keeps URLs consistent)
    const ext = file.name.split(".").pop() || "bin";
    const filename = suggestedFilename || `${crypto.randomUUID()}.${ext}`;

    const uploadsDir = path.join(process.cwd(), "storage", "uploads");
    if (!existsSync(uploadsDir)) {
      await fs.mkdir(uploadsDir, { recursive: true });
    }

    const filePath = path.join(uploadsDir, filename);
    const buffer = Buffer.from(await file.arrayBuffer());
    await fs.writeFile(filePath, buffer);

    return NextResponse.json({ success: true, filename });
  } catch (error) {
    console.error("Storage accept error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Storage failed" },
      { status: 500 }
    );
  }
}
